### ISSUE TITLE
Importe en letras

### ISSUE THREAD

**Issue by adrianpaesani** [ingadhoc/odoo-argentina-ce#14]
Una consulta, la hago por aquí porque no encontré la funcionalidad.
Al emitir una factura no está el importe en letras de la factura, y es uno de los requisitos en la facturación argentina.

**Comment by jjscarafia** [comment]
Buenas @adrianpaesani 
No estoy del todo seguro, pero me suena que revisamos y no era necesario. Tenés la RG/artículo donde figura que es obligatorio?

Saludos!

**Comment by filoquin** [comment]
Cierro por falta de info
