### ISSUE TITLE
Mejora revisores y aprobadores de PR

### ISSUE THREAD

**Issue by jjscarafia** [ingadhoc/odoo-argentina-ce#22]
La idea de este issue es ir mejorando el ciclo de revisión y mezcla de PRs contra este repo

**Comment by jjscarafia** [comment]
@filoquin  @sotolucas
Ahí les di permiso de Triage dentro de los repos, la idea es que puedan mezclar PR's que ya tienen un visto bueno.
No estoy seguro si con eso solo funcionará bien. Cualquier cosa me dicen y lo vamos viendo por acá.

Si algún otro se quiere sumar puede solicitar por este ticket y lo revisamos.

**Comment by sotolucas** [comment]
@jjscarafia buenísimo. Muchas gracias.

**Comment by filoquin** [comment]
@jjscarafia genial.

**Comment by rhe-mastercore** [comment]
Hola @jjscarafia quisiera sumarme, Slds.

**Comment by jjscarafia** [comment]
listo @rhe-mastercore
