### ISSUE TITLE
Error al imprimir o previsualizar un comprobante sin CAE

### ISSUE THREAD

**Issue by daniellibonati** [ingadhoc/odoo-argentina-ce#26]
*Version afectada:*

- 13.0.1.1.0

*Pasos para reproducir:*

1. Intentar imprimir o previsualizar una factura sin CAE (Por ej. las que se cargan como datos de demostración)

*Lo que pasa actualmente:*

- Ocurre el siguiente error:
```
Error to render compiling AST
CacheMiss: ('account.move(18,).afip_qr_code', None)
Template: l10n_ar.report_invoice_document_with_payments
Path: /t/t/t[10]/div/div[1]/img
Node: <img t-if="o.afip_qr_code" t-att-src="'/report/barcode/?type=%s&amp;value=%s&amp;width=%s&amp;height=%s' % ('QR', o.afip_qr_code, 300,300)" alt="qr" style="height:100px"/>
```

*Lo que debe pasar:*

- Debe renderizarse correctamente el comprobante.

*Análisis:*
- El campo `afip_qr_code` es un campo computado que depende del campo `afip_auth_code`. El método que computa dicho campo (`_compute_qr_code`) ignora aquellos registros que no tienen `afip_auth_code` establecido https://github.com/ingadhoc/odoo-argentina-ce/blob/08fe8dba701d4e8e63ab9980c98587193d05b58c/l10n_ar_afipws_fe/models/account_move.py#L103. 
- Asignar `False` a `afip_qr_code` cuando no se da la condición de la línea mencionada corrige el problema.

**Comment by jjscarafia** [comment]
creo que se resolvería con https://github.com/ingadhoc/odoo-argentina-ce/pull/25, no?
en tal caso por favor testear y dar review positivo así avanzamos en la mezcla

**Comment by filoquin** [comment]
Daniel hay un pr que corrije esto #25 . te invito a realizar una review darle ok. Sino @sotolucas  lo miraba hoy.

**Comment by sotolucas** [comment]
@daniellibonati adicionalmente, si vieras que a pesar de actualizar tu clone con el #25 no se imprime, fijate que las dependencias de OCA-web rompen algo (matplotlib y algunas otras).

**Comment by daniellibonati** [comment]
@sotolucas noté lo mismo, estoy buscándole la vuelta. Te aviso cualquier cosa :)

**Comment by filoquin** [comment]
@daniellibonati . Verifica que la versión de Pillow sea 6.2.1 (que la que pide odoo) si tenes pillow 8 no te van a funcionar los  QR.
