### ISSUE TITLE
No se puede instalar en Odoo 16 

### ISSUE THREAD

**Issue by Maurix09** [ingadhoc/odoo-argentina-ce#42]
> **No puedo instalar la localizacion Argentina**
>
> *Version affectada:*
> 
>  - 16 CE
> 
> *Pasos para reproducir:*
> 
>  1. Instalo Ubuntu Server 21
>  2. Instalo Odoo 16 siguiendo los pasos de la pagina de Odoo (https://www.odoo.com/documentation/16.0/administration/install/install.html#prepare)
>  3. Clono los repositorios de odoo-argentina-ce Branch 16.0
> 
> *Lo que pasa actualmente:*
> 
>  - Cuando actualizo las aplicaciones del Odoo, me aparecen los modulos de AFIP, pero sin la opcionde instalar. 
       Cuando vas a "Mas información", dice estado: "Desinstalable". Y no se puede hacer nada.
> 
> *Lo que debe pasar:*
> 
>  - Lo he instalado en Odoo 13, 14 y 15 de la misma manera, y aparece el boton instalar, y luego, obviamente, se instalaba el modulo. Incluso he probado facturar con las 3 versiones sin problemas. 
>

**Comment by filoquin** [comment]
Hola @Maurix09. La localización no tiene versión estable en 16. hay un PR funcional  https://github.com/ingadhoc/odoo-argentina-ce/pull/43 que podes probar y tu review es bienvenida. 

Si no conoces la mecánica del trabajo con PRs te dejo este articulo https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally

Calculo que esta semana estará disponible la versión 16 
Saludos
Filoquin
> > **No puedo instalar la localizacion Argentina**
> > _Version affectada:_
> > 
> > * 16 CE
> > 
> > _Pasos para reproducir:_
> > 
> > 1. Instalo Ubuntu Server 21
> > 2. Instalo Odoo 16 siguiendo los pasos de la pagina de Odoo (https://www.odoo.com/documentation/16.0/administration/install/install.html#prepare)
> > 3. Clono los repositorios de odoo-argentina-ce Branch 16.0
> > 
> > _Lo que pasa actualmente:_
> > 
> > * Cuando actualizo las aplicaciones del Odoo, me aparecen los modulos de AFIP, pero sin la opcionde instalar.
> >   Cuando vas a "Mas información", dice estado: "Desinstalable". Y no se puede hacer nada.
> > 
> > _Lo que debe pasar:_
> > 
> > * Lo he instalado en Odoo 13, 14 y 15 de la misma manera, y aparece el boton instalar, y luego, obviamente, se instalaba el modulo. Incluso he probado facturar con las 3 versiones sin problemas.

**Comment by Maurix09** [comment]
Perfecto.. Voy a probarlo...  No soy implementador, pero se de informatica y ayudo a mi hermano que tiene un almacen a usar el Odoo, y por curiosidad estaba probando el Odoo 16 con la localizacion argentina, porque dicen qaue es mas rapido que las versiones anteriores... Voy a seguir probando y cuando encuentre algun error, les informo para ayudarlos a solucionar el problema.
