### ISSUE TITLE
error qr 

### ISSUE THREAD

**Issue by gbhadolfo** [ingadhoc/odoo-argentina-ce#57]
odoo 16 ce

linea 12 de l10n_ar_afipws_fe/views/report_invoice.xml
`<img t-if="o.afip_qr_code" t-att-src="'/report/barcode/?type=%s&amp;value=%s&amp;width=%s&amp;height=%s' % ('QR', o.afip_qr_code, 300,300)" alt="qr"  style="height:100px"/>`

debe ser

`<img t-if="o.afip_qr_code" t-att-src="'/report/barcode/?barcode_type=%s&amp;value=%s&amp;width=%s&amp;height=%s' % ('QR', o.afip_qr_code, 300,300)" alt="qr"  style="height:100px"/>`

cambiando el nombre del parametro funciona!

**Comment by maq-adhoc** [comment]
https://github.com/ingadhoc/odoo-argentina/pull/798
